baseURL: https://michalmatczuk.dev
languageCode: en-us
title: michalmatczuk.dev

module:
  imports:
    - path: github.com/mrmierzejewski/hugo-theme-console

theme: 'github.com/mrmierzejewski/hugo-theme-console'

params:
  titleCutting: false
  animateStyle: animated zoomIn fast
  navlinks:
    - name: posts/
      url: posts/
    - name: talks/
      url: talks/
    - name: books/
      url: books/
    - name: projects/
      url: projects/
    - name: about/
      url: about/
