baseURL: https://michalmatczuk.dev
languageCode: en-us
title: michalmatczuk.dev

module:
  imports:
    - path: github.com/mrmierzejewski/hugo-theme-console

theme: 'github.com/mrmierzejewski/hugo-theme-console'

params:
  titleCutting: true
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: photos/
      url: photos/
