baseURL: https://michalmatczuk.dev
languageCode: en-us
title: michalmatczuk.dev
enableRobotsTXT: true

params:
  titleCutting: false
  animateStyle: animated zoomIn fast
  navlinks:
    - name: posts/
      url: posts/
    - name: talks/
      url: talks/
    - name: projects/
      url: projects/
    - name: about/
      url: about/

markup:
  highlight:
    codeFences: true
    noClasses: false
    tabWidth: 4
